# Generated by Django 3.1.7 on 2021-07-12 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='job_exp_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=4)),
                ('end_time', models.CharField(max_length=8)),
                ('work_field', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('dtails', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='myprotfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pimage', models.ImageField(upload_to='protfolio')),
                ('category', models.CharField(choices=[('webdevelopment', 'webdevelopment')], max_length=50)),
                ('code_link', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='review_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='review/avatars.jpg', upload_to='review')),
                ('discription', models.TextField()),
                ('profession', models.CharField(max_length=150)),
                ('catagory', models.CharField(choices=[('fiverr', 'fiverr'), ('freeencer', 'freeencer')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dtailprotfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, upload_to='dtail_protfolio')),
                ('img2', models.ImageField(blank=True, upload_to='dtail_protfolio')),
                ('img3', models.ImageField(blank=True, upload_to='dtail_protfolio')),
                ('img4', models.ImageField(blank=True, upload_to='dtail_protfolio')),
                ('img5', models.ImageField(blank=True, upload_to='dtail_protfolio')),
                ('img6', models.ImageField(blank=True, upload_to='dtail_protfolio')),
                ('img7', models.ImageField(blank=True, upload_to='dtail_protfolio')),
                ('img8', models.ImageField(blank=True, upload_to='dtail_protfolio')),
                ('img9', models.ImageField(blank=True, upload_to='dtail_protfolio')),
                ('img10', models.ImageField(blank=True, upload_to='dtail_protfolio')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.myprotfolio')),
            ],
        ),
        migrations.CreateModel(
            name='blog_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog')),
                ('type', models.CharField(max_length=150)),
                ('created', models.DateField(auto_now=True)),
                ('discription', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
